# Generated by Django 5.2.3 on 2025-07-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0725_realmuserdefault_web_left_sidebar_unreads_count_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
