# Generated by Django 5.2.3 on 2025-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0731_stream_can_delete_any_message_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
