# Generated by Django 5.2.3 on 2025-07-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0729_alertword_deactivated"),
        ("zerver", "0733_set_default_value_for_can_delete_any_message_group"),
        ("zerver", "0735_alter_stream_can_delete_any_message_group"),
        ("zerver", "0738_set_default_value_for_can_delete_own_message_group"),
        ("zerver", "0743_set_default_value_for_can_set_delete_message_policy_group"),
    ]

    operations = []
