# Generated by Django 5.2.4 on 2025-08-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0748_channelfolder_add_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertword",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
